# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
#baseurl = "https://huangbaihua-blog-6fodlgn2bee81bf-1301217831.tcloudbaseapp.com/"  # Include trailing slash
baseurl = "https://huangbaihua001.github.io/me/"
title = "baihua.huang"
author = "Keepwalking(baihua.huang)"
copyright = "Copyright © 2008–2022, Keepwalking; all rights reserved. Powered by Hugo"
# canonifyurls = true
paginate = 10
theme = "github.com/chipzoller/hugo-clarity"

disqusShortname = ""

DefaultContentLanguage = "zh"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false