# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://huangbaihua.gitee.io/"  # Include trailing slash
title = "baihua.huang"
author = "柏华(baihua.huang)"
copyright = "Copyright © 2008–2021, 柏华; all rights reserved. Powered by Hugo"
# canonifyurls = true
paginate = 10
theme = "github.com/chipzoller/hugo-clarity"

disqusShortname = ""

DefaultContentLanguage = "zh"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false