# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://huangbaihua.gitee.io/"  # Include trailing slash
title = "baihua.huang"
author = "黄柏华(baihua.huang)"
copyright = "Copyright © 2008–2021, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "github.com/chipzoller/hugo-clarity"

disqusShortname = ""

DefaultContentLanguage = "zh"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
